version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
  node:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO=mongodb://mongo
    depends_on:
      - mongo
volumes:
  db: