version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
  redis:
    image: redis
    restart: always
  node:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO=mongodb://mongo
      - REDIS=redis://redis
    depends_on:
      - mongo
      - redis
volumes:
  db:
